### ISSUE TITLE
Problematic behavior of sov-modules-macros

### ISSUE THREAD

**Issue by pepyakin** [Sovereign-Labs/sovereign-sdk#1204]
First, constants.json can't be found when overriding CARGO_TARGET_DIR. E.g.

```
error: failed to run custom build command for `sov-modules-macros v0.3.0 (https://github.com/Sovereign-Labs/sovereign-sdk?rev=6058b31#6058b315)`

Caused by:
  process didn't exit successfully: `/tmp/cargo_target/debug/build/sov-modules-macros-ab937429e27a4739/build-script-build` (exit status: 1)
  --- stderr
  Error: Could not find a parent `constants.json`
```

Second,

https://github.com/Sovereign-Labs/sovereign-sdk/blob/a099cb3ce9230f0aba8c507123e8375b06a93fc2/module-system/sov-modules-macros/build.rs#L52

It writes at CARGO_MANIFEST_DIR, which is, quote:

> The directory containing the manifest for the package being built (the package containing the build script).

Generally, source tree is considered to be immutable and is not recommended to write to (a canonical example of that is `git submodule update`). One particular outcome of this, is that the build modifies `$CARGO_HOME/git/checkouts` — a global per-machine immutable registry — which sounds rather dodgy.

Tagging @preston-evans98 from blame of the last change.

**Comment by pepyakin** [comment]
Ok, what I thought to be the last version wasn't actually the last. I also found this https://github.com/Sovereign-Labs/sovereign-sdk/pull/1154 which is one of the example problems you would expect from this kind of thing.

I also spent some time to look at the code trying to understand why exactly you want to do that. So it seems like the intended behavior is that the `constants.json` should be in the source tree of the user rollup, and in their runtime they would use the `#[config_constant]` proc-macro. That proc-macro impl tries to read that const from the json file and embed the value. However, it's problematic to reach to constants.json because we don't know the manifest dir of the user's rollup.

Tricky. 

UPD: Well, I realized that sqlx solves this somehow and yes, they do [this hack](https://github.com/launchbadge/sqlx/blob/929af41745a9434ae83417dcf2571685cecca6f0/sqlx-macros-core/src/query/mod.rs#L83-L103). It seems to work if I use this code in `read_constants` in `sov-modules-macros`, not sure how robust is that though.

**Comment by preston-evans98** [comment]
Hey @pepyakin! Thanks for the report. We've been planning a fix for these issues internally for a bit now, but I wasn't aware of the sqlx example. That looks pretty decent! Would you mind sharing the branch where you played around with it?

**Comment by preston-evans98** [comment]
cc @vlopes11, I think the decision to mutate the source tree was motivated by wanting to support users putting the `constants.json` file in different locations. Is that right? If so, are there any barriers to eliminating that functionality and just forcing them to use the workspace root?

**Comment by vlopes11** [comment]
@preston-evans98 The original motivation for having multiple `constants.json` files per module, with fallback to the root workspace, has evolved. Now, it makes more sense to have a single `constants.json` file per binary endpoint. This would provide greater consistency. The `target-path` source tree write was initially used as a hack to enable the macro expansion phase to be aware of the absolute path to the module library, allowing it to traverse upwards to the workspace root. However, since we now have a single `constants.json` file per binary endpoint, this hack can be safely removed. We can read the file from the workspace root using the sqlx trick. Additionally, we discussed the possibility of having the config located in the home config folder of the user, such as `$HOME/.config/sovereign/<rollup-id>/constants.json`.

**Comment by preston-evans98** [comment]
Awesome, thanks @vlopes11! I think it's probably preferable to have the constants file live in the workspace root for now. That will make it easy to discover and ensure that it's tracked in version control.
